### ISSUE TITLE
attention map of L-Net

### ISSUE THREAD

**Issue by maogewudi007** [buxiangzhiren/ContextLoc#3]
arxiv上版本:
![image](https://user-images.githubusercontent.com/25141812/132981289-575b720e-72f6-4d66-a807-cdf3ca00bcd8.png)

计算  L-Net attention map权重的时候, 不考虑 视频全局特征z。

但是在代码实现部分：
<img width="795" alt="截屏2021-09-12 下午4 49 53" src="https://user-images.githubusercontent.com/25141812/132981350-5dfbcc46-72d3-4378-aa36-045369f2fd3f.png">
把 视频全局特征z，用上了 ？

** L-Net attention map 的计算方式，论文书写 和 最终代码实现 是不一致的吗？**

**Comment by buxiangzhiren** [comment]
当时我们在写论文的时候没有加入z在L-Net，后面整理代码的时候为了对称性加入了。然后发现性能还能有些提升，你可以试着去掉z看看性能，波动在大概0.1%~0.2%，没有什么影响。
